### ISSUE TITLE
Access violation

### ISSUE THREAD

**Issue by Dagur** [eSlider/sassc-binaries#8]
Hi

I'm on windows 10 and sassc.exe crashes when I try to use it, something about an access violation.

I hope this tells you something

`Faulting application name: sassc.exe, version: 0.0.0.0, time stamp: 0x54bd1bbf
Faulting module name: MSVCR120.dll, version: 12.0.21005.1, time stamp: 0x524f7ce6
Exception code: 0xc0000005
Fault offset: 0x000182a7
Faulting process id: 0x4434
Faulting application start time: 0x01d33b6ea577529a
Faulting application path: C:\GIT\sassc-binaries\dist\sassc.exe
Faulting module path: C:\GIT\sassc-binaries\dist\MSVCR120.dll
Report Id: a45907c6-5847-4a95-a98f-0b78f8763d75
Faulting package full name: 
Faulting package-relative application ID: `

**Comment by eSlider** [comment]
@Dagur, `MSVCR120.dll` is an redistributable library file of Microsoft Visual C++ Redistributable Packages for Visual Studio 2013.
Please try to remove library file `C:\GIT\sassc-binaries\dist\MSVCR120.dll`  and 
 install original package https://www.microsoft.com/en-en/download/details.aspx?id=40784

**Comment by Dagur** [comment]
That link doesn't work :/

**Comment by eSlider** [comment]
@Dagur, https://www.microsoft.com/en-US/download/details.aspx?id=40784

**Comment by Dagur** [comment]
Tried it and didn't work. This isn't a huge issue for me anymore since I just used the node version instead.
